In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('../../Downloads/datasets/Obesity Classification.csv')

In [3]:
df

      ID  Age  Gender  Height  Weight   BMI          Label
0      1   25    Male     175      80  25.3  Normal Weight
1      2   30  Female     160      60  22.5  Normal Weight
2      3   35    Male     180      90  27.3     Overweight
3      4   40  Female     150      50  20.0    Underweight
4      5   45    Male     190     100  31.2          Obese
..   ...  ...     ...     ...     ...   ...            ...
103  106   11    Male     175      10   3.9    Underweight
104  107   16  Female     160      10   3.9    Underweight
105  108   21    Male     180      15   5.6    Underweight
106  109   26  Female     150      15   5.6    Underweight
107  110   31    Male     190      20   8.3    Underweight

[108 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      108 non-null    int64
 1   Age     108 non-null    int64
 2   Gender  108 non-null    object
 3   Height  108 non-null    int64
 4   Weight  108 non-null    int64
 5   BMI     108 non-null    float64
 6   Label   108 non-null    object
dtypes: float64(1), int64(4), object(2)
memory usage: 6.0+ KB

In [5]:
df['Label'].value_counts()

Label
Underweight      47
Normal Weight    29
Overweight       20
Obese            12
Name: count, dtype: int64

In [6]:
df['Gender']=df['Gender'].map({'Male':0, 'Female': 1})
code_1 = {'Underweight': 0, 'Normal Weight': 1, 'Overweight': 2, 'Obese':3}
df['Label']= df['Label'].map(code_1)

In [7]:
df

      ID  Age  Gender  Height  Weight   BMI  Label
0      1   25       0     175      80  25.3      1
1      2   30       1     160      60  22.5      1
2      3   35       0     180      90  27.3      2
3      4   40       1     150      50  20.0      0
4      5   45       0     190     100  31.2      3
..   ...  ...     ...     ...     ...   ...    ...
103  106   11       0     175      10   3.9      0
104  107   16       1     160      10   3.9      0
105  108   21       0     180      15   5.6      0
106  109   26       1     150      15   5.6      0
107  110   31       0     190      20   8.3      0

[108 rows x 7 columns]

In [8]:
X = df[['Age', 'Gender', 'Height', 'Weight', 'BMI']]
y = df['Label']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test= train_test_split(X,y, test_size=0.30, random_state=100)
X_train.shape,y_train.shape

((75, 5), (75,))

In [10]:
import matplotlib.pyplot as plt

In [11]:
df.corr()

              ID       Age    Gender    Height    Weight       BMI     Label
ID      1.000000 -0.298257  0.005595 -0.008224 -0.572625 -0.615235 -0.459655
Age    -0.298257  1.000000  0.091964 -0.076896  0.465106  0.474185  0.451868
Gender  0.005595  0.091964  1.000000 -0.876225 -0.418415 -0.342342 -0.405208
Height -0.008224 -0.076896 -0.876225  1.000000  0.428890  0.354340  0.428596
Weight -0.572625  0.465106 -0.418415  0.428890  1.000000  0.972829  0.935518
BMI    -0.615235  0.474185 -0.342342  0.354340  0.972829  1.000000  0.871449
Label  -0.459655  0.451868 -0.405208  0.428596  0.935518  0.871449  1.000000

In [12]:
df['Age'].sort_values(ascending=False)

57     112
28     108
56     107
27     103
55     102
      ...
68      15
78      14
83      13
93      12
103     11
Name: Age, Length: 108, dtype: int64

In [13]:
df['Height'].sort_values(ascending=False)

66     210
101    210
91     210
36     210
8      210
      ...
92     120
102    120
57     120
19     120
9      120
Name: Height, Length: 108, dtype: int64

In [14]:
X_train.head()

    Age  Gender  Height  Weight   BMI
92   58       1     120      35  16.7
20   68       0     175      80  25.3
37   64       1     120      95  29.1
6    55       0     200     110  34.2
3    40       1     150      50  20.0

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled= scaler.transform(X_train)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [17]:
models = {'LogisticRegression': LogisticRegression(),
        'KNN1': KNeighborsClassifier(n_neighbors= 1),
        'KNN3': KNeighborsClassifier(n_neighbors= 3),
        'KNN5': KNeighborsClassifier(n_neighbors= 5),
        'KNN7': KNeighborsClassifier(n_neighbors= 7),
        'KNN9': KNeighborsClassifier(n_neighbors= 9)}

In [18]:
X_test_scaled=scaler.transform(X_test)

In [19]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    score=model.score(X_test_scaled, y_test)
    print(name, score)

LogisticRegression 0.6666666666666666
KNN1 0.8484848484848485
KNN3 0.7575757575757576
KNN5 0.8181818181818182
KNN7 0.8181818181818182
KNN9 0.7575757575757576

In [20]:
test=[[35, 0, 180, 90, 27.3], [25,0, 175, 80, 25.3]]

In [21]:
test_scaled =scaler.transform(test)
model.predict(test_scaled)

c:\Users\SUCHITRA KADAM\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

array([2, 1], dtype=int64)

In [22]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    predict = model.predict(test_scaled)
    print(name, predict)

LogisticRegression [1 1]
KNN1 [2 1]
KNN3 [2 1]
KNN5 [2 1]
KNN7 [2 1]
KNN9 [2 1]

In [23]:
final_model = KNeighborsClassifier(n_neighbors= 5)
final_model.fit(X_train_scaled, y_train)
X=scaler.transform(X)
yp=final_model.predict(X)

In [24]:
predict = final_model.predict(test_scaled)
print(predict)

[2 1]

In [25]:
import pickle
pickle.dump(final_model, open('final_model.pkl', 'wb'))
pickle.dump(scaler,open('scaler.pkl', 'wb'))